version: "3"
services:
  selenium-hub:
    image: selenium/hub:last
    container_name: selenium-hub
    ports:
      - "4444:4444"
    expose:
      - 4444
  chrome:
    image: selenium/node-chrome-debug:last
    container_name: chrome
    deploy:
      replicas: 5
    ports:
      - "5900:5900"
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
  # coreapiselenium:
  #   image: coreapiselenium
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: coreapiselenium
  #   ports:
  #     - "8080:80"
